In [1]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [24]:
#파이썬으로는 하나하나가 데이터라서 꺼내서 돌려야 하는데,
x=[]
for i in [-1,1,3,1]:
    x.append(abs(i))
print(x)        

[1, 1, 3, 1]


In [21]:
[abs(i) for i in [-1,1,3,1]]

[1, 1, 3, 1]

In [23]:
#numpy는 넘파이 어레이에서 통째로 돌아간다.
np.abs([-1,1,3,1])

array([1, 1, 3, 1])

In [29]:
#all은 다 맞으면 True, 하나라도 0이 있으면 False -> AND 연산
print(np.all([1,2,3]))
print(np.all([0,1,2]))
print(np.all([-1,1,2]))

True
False
True


In [30]:
#any는 하나라도 맞으면 True, 다 0이면 Flase -> OR 연산
print(np.any([1,2,3]))
print(np.any([0,0,2]))
print(np.any([-1,1,2]))

True
True
True


In [38]:
arr=np.array([1,2,3,4])
np.append(arr,10) #np.array는 함수로서 객체값을 변화시키지 않고 리턴값만 돌려준다.

array([ 1,  2,  3,  4, 10])

In [39]:
arr

array([1, 2, 3, 4])

In [40]:
arr=np.append(arr,10)

In [41]:
arr

array([ 1,  2,  3,  4, 10])

In [43]:
n_range = np.arange(1,11) #값
r = range(1,11)           #제네레이터

In [46]:
r+1

TypeError: unsupported operand type(s) for +: 'range' and 'int'

이미 값인 상태라 더 빠르게 돌려진다

In [48]:
m1 = np.arange(20).reshape(4,5)

In [49]:
m1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
#10을 넣을 곳이 없어서 풀어버리고 넣어준다.
np.append(m1,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 10])

In [102]:
import pandas as pd
np.random.seed(100)
df = pd.DataFrame(np.random.randint(1,20,size=(10000000,5)))

df는 짝수가 몇개인지?

In [103]:
df.shape

(10000000, 5)

가능하면 numpy돌리면 무조건 좋다.

In [108]:
np.sum((df+1)%2,1)

0          3
1          0
2          2
3          2
4          2
          ..
9999995    2
9999996    4
9999997    3
9999998    1
9999999    3
Length: 10000000, dtype: int64

삼항 연산자 두개중에 맞으면 표현하는 것 (조건,true일때 값, false일때 값)<br>
넘파이는 np.where

In [106]:
x = np.array([2,1,2,1,2,2,2])
np.where(x==1,True,False)

array([False,  True, False,  True, False, False, False])

In [109]:
def xx(x):
    return np.sum(np.where(x%2==0,1,0))

In [111]:
#a = df.apply(xx,1) #오오래걸림

In [115]:
#df.apply(lambda x: np.sum(np.where(x%2==0,1,0)),1) #이것도 오오래 걸림, 형태는 이거 권장

In [118]:
a=np.apply_along_axis(xx,1,df.values)
#a = df.apply(xx,1)

In [128]:
import math
math.sin(np.pi/2)
np.sin(np.pi/2)

1.0

In [129]:
np.e

2.718281828459045

In [144]:
arr = np.array([2,3,4])
np.argmax(arr) #argument중에 가장 큰 값이 있는 곳
np.argmin(arr) #argument중에 가장 작은 값이 있는 곳
np.min(arr)
np.max(arr)
np.sort(arr)

array([2, 3, 4])

In [145]:
np.argsort(arr) #argument 오차순 순서 어레이 중요!!!

array([0, 1, 2], dtype=int64)

In [138]:
np.argsort??

Signature:       np.argsort(a, axis=-1, kind=None, order=None)
Call signature:  np.argsort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function argsort at 0x0000020CB26C32E0>
File:            c:\users\user\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Source:         
@array_function_dispatch(_argsort_dispatcher)
def argsort(a, axis=-1, kind=None, order=None):
    """
    Returns the indices that would sort an array.

    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.

    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorith

#중요도 순서             <br>
np.argsort(arr) #1      <br>
np.argmax(arr) #2       <br>
np.argmin(arr) #2       <br>
np.min(arr)     #3      <br>
np.max(arr)     #3      <br>
np.sort(arr)    #4

In [149]:
#round([7/96,5/13],2)

In [150]:
np.around([7/96, 5/13],2)

array([0.07, 0.38])

In [151]:
m1 = np.random.randint(1,10,size=(2,3))
m2 = np.random.randint(1,10,size=(3,2))

#np.asmatrix()

In [152]:
type(m1)

numpy.ndarray

In [153]:
m1.shape

(2, 3)

In [154]:
np.dot(m1,m2)

array([[ 83,  50],
       [104,  74]])

In [155]:
m1*m2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [157]:
m3 = np.asmatrix(m1)
m4 = np.asmatrix(m2)

In [160]:
np.dot(m3,m4)

matrix([[ 83,  50],
        [104,  74]])

In [158]:
m3*m4

matrix([[ 83,  50],
        [104,  74]])

np.asmatrix를 하기 전까진 matrix가 아니라 n차원 array취급이다.

In [165]:
np.byte(m1)

array([[4, 3, 6],
       [7, 6, 3]], dtype=int8)

In [166]:
import sys
sys.getsizeof([1,2,3])

88

In [172]:
r=range(1,100000000)

In [173]:
sys.getsizeof(r)

48

In [174]:
r1=list(range(1,1000000))

In [175]:
sys.getsizeof(r1)

8000056

메모리 영향을 줄이기 위해서 제네레이터를 사용한다.